### ISSUE TITLE
Record/Replay keyboard input

### ISSUE THREAD

**Issue by stbornowski** [tomgallagher/RecordReplay#4]
Hi Thomas 

As I mentioned yesterday in my email, I tried to record our login view. Unfortunaly the replay of the recording has failt.

I made the following example for this issue: 
- Open our login page
- Insert the wrong credentials (Navigation by tabbing or mouse clicks)
- Validating that the message "credentials are wrong" will be visible.

Could please fix this issue with the attached files?

Thanks in advance! 
[GitHub_Replay.zip](https://github.com/tomgallagher/RecordReplay/files/5621480/GitHub_Replay.zip)

**Comment by tomgallagher** [comment]
Perfect. Leave that with me. I'm assuming it's OK to just load up the JSON and try to find the bug at my end?

**Comment by tomgallagher** [comment]
Early signs are that Chrome have changed the permissioning for the use of the debugger via the extensions API in the latest version.

**Comment by tomgallagher** [comment]
OK. I have both of your examples working now. I am recording the input change events **and** the keystroke events, so you may want to delete the input change event from your recording before replaying.

Just need to run some tests tomorrow and then I'll push a new version.

**Comment by tomgallagher** [comment]
Version 1.0.1.5 pushed out for review just now. I've tested extensively on your example and it all works fine.

Closing this for now but get in touch if there are any problems
