### ISSUE TITLE
Can't export code/replay

### ISSUE THREAD

**Issue by patrick-mota** [tomgallagher/RecordReplay#8]
**Describe the bug**
Can't export record/replay with testingLibrary, cypress and puppeteer.

**To Reproduce**

I tried first with Edge Chromium and had this error.

Then I tried with Chrome (v. 87.0.4280.141) and had the exact same problem.

1. Created a new project
2. Created a new test with Start URL www.google.fr, Bandwidth none, Minimum Latency None, and no other option check
3. New Recording for Device Computer
3. After New Recording Created, click Start
4. Do what you want
5. Stop
6. Try to export the replay or record, if you click in Cypress, Puppeteer or testingLibrary it doesn't work, nothing appears and in the console I got an error

**Expected behavior**
Download the Cypress code.

**Screenshots**
![image](https://user-images.githubusercontent.com/4503898/103994139-dc6ce380-5196-11eb-8e79-8a0ebcef8348.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge Chromium and Chrome
 - Chrome (v. 87.0.4280.141)

**Additional context**
Just a thank you for RecordReplay

**Comment by tomgallagher** [comment]
OK leave it with me. I'll check it out.

**Comment by tomgallagher** [comment]
Found the problem. Thanks for reporting it. Error was introduced on last version. Now fixed in version 1.0.1.6, which is currently being reviewed by Chrome and should be in the Chrome Web Store by the end of today. Please update to latest version when you can. Then let me know if this bug is fixed.

**Comment by tomgallagher** [comment]
Version 1.0.1.6 now in the Chrome Web Store.

**Comment by patrick-mota** [comment]
Very fast thank you @tomgallagher !
I tried in Edge Chromium and seems working now.
I can see some enhancement for RecordReplay and if I can contribute I'll.

Thank you again and have a nice week-end !

**Comment by tomgallagher** [comment]
No problem. 

I think there's definitely a space for a Chromium-based open source testing framework with lots of contributors. The accelerating uptake of this extension over the last few months indicates that. 

The main thing is to raise the profile and you can help by reviewing on the Chrome Web Store, esp relating to bug fixes and responsiveness of owner, and/or starring the Github repo, 

Good weekend!
